# Generated by Django 2.2 on 2020-01-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('New_app', '0002_auto_20200129_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('champion', models.CharField(max_length=255)),
                ('build', models.CharField(max_length=255)),
                ('lane', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by', to='New_app.User')),
            ],
        ),
    ]
